### ISSUE TITLE
Set kanban boar for final capstone project. 

### ISSUE THREAD

**Issue by Baroka-wp** [Baroka-wp/yatch_house#22]
### Set kanban boar for final capstone project. 
We are **5** people in the group : 
- @Yazino12 
- @rolandfbk 
- @kwambiee 
- @Baroka-wp 
- @GedeonTS 

The project link => https://github.com/Baroka-wp/yatch_house/projects/1

![Kanbanboard Screenshot](https://user-images.githubusercontent.com/43172164/190398556-51c3c69b-178a-461b-b1f3-1d5d9e526ffd.png)

**Comment by mcrd25** [comment]
Hi Team (@rolandfbk @Yazino12 @kwambiee @Baroka-wp @GedeonTS), 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Yazino12** [comment]
@mcrd25, Thanks for pointing that crucial point out 🙏🏽. We will implement the change right away ✔.

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
